### ISSUE TITLE
Exe file in dir with spaces

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_lint_autoit#2]
change the line
cmd = 'Au3Check -q'
in linter.py to the correct path.

What to do if dir has Spaces in it?

**Comment by TomBraider42** [comment]
Just use quotes. And i think everyone who change the code will know it.
cmd = '"Path Au3Check" -q'
But the Batch file option i "borrowed" from cuda_lint_javac is the cleaner/better way.
