### ISSUE TITLE
Port 2 linters?

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_lint_autoit#3]
Hi again
Maybe you can help to port 2 linters to CudaLint...
they have big DL counters. (if you see all linters.)
https://packagecontrol.io/packages/SublimeLinter-contrib-ansible-lint
https://packagecontrol.io/packages/SublimeLinter-contrib-gcc

**Comment by TomBraider42** [comment]
Perhaps gcc, but i never heard about ansible.

**Comment by Alexey-T** [comment]
Ok, GCC is good
Maybe you know other langs?

**Comment by TomBraider42** [comment]
Take a look to https://github.com/TomBraider42/cuda_lint_gcc
I'm in web development, not using C/C++, so i can't really check it.

**Comment by Alexey-T** [comment]
It is good- thanks! 
![gcc](https://cloud.githubusercontent.com/assets/4154978/26191927/80dfe2e4-3bb8-11e7-9433-41eb9549eb78.png)

**Comment by Alexey-T** [comment]
Which frameworks for web, are you using?
