### ISSUE TITLE
Ability to use portable mode

### ISSUE THREAD

**Issue by Skif-off** [TomBraider42/cuda_lint_autoit#4]
Please add the ability to use as portable, for example:
```diff
from cuda_lint import Linter, util
+import os
...
    cmd = 'Au3Check -q'
+    #cmd = os.path.dirname(__file__.replace('\\', '/')) + '/Au3Check.exe -q' 
```

**Comment by Alexey-T** [comment]
Need change in linter.py:

- import os
- commented line, which sets path to Exe with portable dir: 

`... = os.path.join(os.path.dirname(__file__), 'au3check.exe')`

user can uncomment this one line, and he has portable mode. he copies au3check.exe too.

**Comment by Skif-off** [comment]
**Alexey-T**, у меня так почему-то не работало, точнее, работало, но чуть-чуть: в строку статуса писал ```Linter "autoit" found no errors``` и всё, хотя ошибок наделал кучу.
Если добавить ```-q```
```
os.path.join(os.path.dirname(__file__), 'au3check.exe -q')
```
тогда в вывод писалось:
```
ERROR: autoit cannot locate 'C:UtilitiesCudapycuda_lint_autoitAu3Check.exe'
```
Из чего сделал предположение, что обратные слэши в строке не перевариваются и намудрил с ```replace```... Но заработало :)

**Comment by Alexey-T** [comment]
это потому что -q надо писать как отдельный элемент, кажется так типа- .... = (path, '-q'), и еще перед строкой с слешем надо ставить r - `r'c:\path\test.exe'`.

**Comment by TomBraider42** [comment]
Please write in english or i will delete the posts.
It's my site so i want to be able to read all comments.

**Comment by Alexey-T** [comment]
My 1st comment is full info. User replied that he dont know Python and tries to write some hack to linter.py to use portable EXE

**Comment by TomBraider42** [comment]
Portable:
- copy `Au3Check.exe` and `Au3Check.dat` to `cuda_lint_autoit` dir
- change the path to
`cmd = os.path.join(os.path.dirname(__file__), 'Au3Check.exe -q -I').replace('\\', '/')`

But you will get a lot of errors if you include default UDFs, because the linter don't know the include AutoIt directory.
See the readme for the batch file solution.

**Comment by Skif-off** [comment]
Why are you using ```-I``` without ```dir```?

P.S. If some user is using a portable version, then he understands what he is doing and he is able to solve his problems ;)

**Comment by TomBraider42** [comment]
The linter uses a temp file with all unsaved changes. After the `-I` the dir of the original file will be added automatically. So all local includes will be found. But no UDFs from the unknown AutoIt dir.
